### ISSUE TITLE
Plugin does not load to jedit

### ISSUE THREAD

**Issue by kabirkbr** [ontologyportal/SUMOjEdit#2]
if plugin compiled with jdk-16.0.1:

![image](https://user-images.githubusercontent.com/1760288/117130888-f4e5b700-ada0-11eb-9321-8008c2fb96d3.png)

if compiled with java-11-openjdk-amd64:
![image](https://user-images.githubusercontent.com/1760288/117131161-5c036b80-ada1-11eb-8fb9-ba215df10e30.png)

I think it would be a good idea to include jdk versions in the installation instructions as it is not obvious where to find them. Thanks.

**Comment by apease** [comment]
Many thanks for pointing out the problem with JDK versions.  There are so many now!  But I do point out the need to install the Sun/Oracle JDK in the Sigma README at line 181, and I provide a link.  I suspect others JDKs will work, but if you want to use another you're on your own.  I'd welcome testing reports of which ones do/don't work though, and maybe I should have a more prominent warning about this.

**Comment by kabirkbr** [comment]
@apease -- thanks for the quick reply. i missed that line. maybe a more prominent warning would be nice -- i was assuming that the latest java version should work...

you are right, java versions are a mess... it is still somewhat confusing (at least for non-java non-gurus), since the line 181 seem to point to jdk1.8.0_291, while 190 points to jdk-14.0.1_linux-x64_bin.tar.gz and I cannot seem to make sense if there's any difference... anyway, probably oracle to blame for this...

btw, i made a shell script for running the Linux Install part of the readme -- see attached, if that helps in any way.

```
#!/bin/bash

# comment out the following lines to turn off line-by-line mode
set -x
trap read debug

# install everything on sumo directory under home
cd ~
mkdir sumo
cd sumo
mkdir workspace
mkdir Programs
cd Programs
wget 'https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.23/bin/apache-tomcat-8.5.23.zip'
wget 'http://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz'
wget 'http://wwwlehre.dhbw-stuttgart.de/~sschulz/WORK/E_DOWNLOAD/V_2.0/E.tgz'
tar -xvzf E.tgz
unzip apache-tomcat-8.5.23.zip
rm apache-tomcat-8.5.23.zip
cd ~/sumo/Programs/apache-tomcat-8.5.23/bin
chmod 777 *
cd ../webapps
chmod 777 *
cd ~/sumo/workspace/
sudo apt-get install git
git clone https://github.com/ontologyportal/sigmakee
git clone https://github.com/ontologyportal/sumo
cd ~
mkdir .sigmakee
cd .sigmakee
mkdir KBs
cp -R ~/sumo/workspace/sumo/* KBs
me="$(whoami)"
cp ~/sumo/workspace/sigmakee/config.xml ~/.sigmakee/KBs
sed -i "s/theuser/$me/g" KBs/config.xml
cd ~/sumo/Programs
gunzip WordNet-3.0.tar.gz
tar -xvf WordNet-3.0.tar
cp WordNet-3.0/dict/* ~/.sigmakee/KBs/WordNetMappings/
cd ~/sumo/Programs/E
sudo apt-get install make
sudo apt-get install gcc
./configure
make
make install
cd ~
sudo apt-get install graphviz
echo "export SIGMA_HOME=~/.sigmakee" >> .bashrc
echo "export SIGMA_SRC=~/sumo/workspace/sigmakee" >> .bashrc
echo "export ONTOLOGYPORTAL_GIT=~/sumo/workspace" >> .bashrc
echo "export CATALINA_OPTS=\"$CATALINA_OPTS -Xms500M -Xmx7g\"" >> .bashrc
echo "export CATALINA_HOME=~/sumo/Programs/apache-tomcat-8.5.23" >> .bashrc
source .bashrc
cd ~/sumo/workspace/sigmakee
sudo add-apt-repository universe
sudo apt-get update
sudo apt-get install ant
ant
```

**Comment by apease** [comment]
thanks @kabirkbr having a script for install is a good idea, since it's so complicated, but the problem is that the filenames that are the target of the wget seem to change, and some people have different system configurations etc.  What we really need is someone with experience creating installers to create a .deb and/or .rpm for Sigma (and an .exe for windows and .bin for Mac would be great too!).  Alas I don't know how but we may have a kind volunteer working on a .deb at the moment...

**Comment by kabirkbr** [comment]
*.deb is an option, but honestly, i do not like them for development environment where i feel that some more control over where config files are placed. it is usually quite complicated to figure out where deb puts config directories.

btw, another note, it may make sense to indicate in the readme that the first run of the plugin takes about 10 minutes to load and it throws some error on command line. At first I thought that there is another problem...

```
9:41:13 PM [main] [warning] SUMOjEdit: SUMOjEdit(): initializing
9:43:15 PM [main] [error] main: java.io.FileNotFoundException: /home/kabir/.sigmakee/KBs/WordNetMappings/omw.ser (No such file or directory)
9:43:15 PM [main] [error] main:  at java.base/java.io.FileInputStream.open0(Native Method)
9:43:15 PM [main] [error] main:  at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
9:43:15 PM [main] [error] main:  at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
9:43:15 PM [main] [error] main:  at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
9:43:15 PM [main] [error] main:  at com.articulate.sigma.wordNet.OMWordnet.loadSerialized(OMWordnet.java:275)
9:43:15 PM [main] [error] main:  at com.articulate.sigma.wordNet.OMWordnet.readOMWfiles(OMWordnet.java:327)
9:43:15 PM [main] [error] main:  at com.articulate.sigma.KBmanager.setConfiguration(KBmanager.java:687)
9:43:15 PM [main] [error] main:  at com.articulate.sigma.KBmanager.initializeOnce(KBmanager.java:644)
9:43:15 PM [main] [error] main:  at com.articulate.sigma.KBmanager.initializeOnce(KBmanager.java:582)
9:43:15 PM [main] [error] main:  at com.articulate.sigma.jedit.SUMOjEdit.<init>(SUMOjEdit.java:71)
9:43:15 PM [main] [error] main:  at com.articulate.sigma.jedit.SUMOjEditPlugin.<clinit>(SUMOjEditPlugin.java:33)
9:43:15 PM [main] [error] main:  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
9:43:15 PM [main] [error] main:  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
9:43:15 PM [main] [error] main:  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
9:43:15 PM [main] [error] main:  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
9:43:15 PM [main] [error] main:  at java.base/java.lang.Class.newInstance(Class.java:584)
9:43:15 PM [main] [error] main:  at org.gjt.sp.jedit.PluginJAR.activatePlugin(PluginJAR.java:933)
9:43:15 PM [main] [error] main:  at org.gjt.sp.jedit.PluginJAR.activatePluginIfNecessary(PluginJAR.java:1021)
9:43:15 PM [main] [error] main:  at org.gjt.sp.jedit.jEdit.main(jEdit.java:553)
9:51:58 PM [main] [error] main: java.io.IOException: Cannot run program "/home/kabir/E/bin/e_ltb_runner": error=2, No such file or directory
9:51:58 PM [main] [error] main:  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
9:51:58 PM [main] [error] main:  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
9:51:58 PM [main] [error] main:  at com.articulate.sigma.tp.EProver.<init>(EProver.java:191)
9:51:58 PM [main] [error] main:  at com.articulate.sigma.KB.loadEProver(KB.java:3407)
9:51:58 PM [main] [error] main:  at com.articulate.sigma.KBmanager.loadKBforInference(KBmanager.java:409)
9:51:58 PM [main] [error] main:  at com.articulate.sigma.KBmanager.initializeOnce(KBmanager.java:654)
9:51:58 PM [main] [error] main:  at com.articulate.sigma.KBmanager.initializeOnce(KBmanager.java:582)
9:51:58 PM [main] [error] main:  at com.articulate.sigma.jedit.SUMOjEdit.<init>(SUMOjEdit.java:71)
9:51:58 PM [main] [error] main:  at com.articulate.sigma.jedit.SUMOjEditPlugin.<clinit>(SUMOjEditPlugin.java:33)
9:51:58 PM [main] [error] main:  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
9:51:58 PM [main] [error] main:  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
9:51:58 PM [main] [error] main:  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
9:51:58 PM [main] [error] main:  at okokjava.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
9:51:58 PM [main] [error] main:  at java.base/java.lang.Class.newInstance(Class.java:584)
9:51:58 PM [main] [error] main:  at org.gjt.sp.jedit.PluginJAR.activatePlugin(PluginJAR.java:933)
9:51:58 PM [main] [error] main:  at org.gjt.sp.jedit.PluginJAR.activatePluginIfNecessary(PluginJAR.java:1021)
9:51:58 PM [main] [error] main:  at org.gjt.sp.jedit.jEdit.main(jEdit.java:553)
9:51:58 PM [main] [error] main: Caused by: java.io.IOException: error=2, No such file or directory
9:51:58 PM [main] [error] main:  at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
9:51:58 PM [main] [error] main:  at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
9:51:58 PM [main] [error] main:  at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
9:51:58 PM [main] [error] main:  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
9:51:58 PM [main] [error] main:  ... 16 more
9:51:58 PM [main] [warning] SUMOjEdit: SUMOjEdit(): kb: SUMO : 88698 formulas
```
second run seems a bit shorter:
```
10:09:31 PM [main] [warning] SUMOjEdit: SUMOjEdit(): initializing
10:11:57 PM [main] [warning] SUMOjEdit: SUMOjEdit(): kb: SUMO : 88698 formulas
```
in both cases, the plugin is working -- so thanks @apease. btw, i sent you a message on researchgate -- a response would be much appreciated if possible ;).

**Comment by apease** [comment]
@kabirkbr I'm afraid I rarely use ResearchGate.  Most of my papers are at https://adampease.org or feel free to email me

**Comment by apease** [comment]
subsequent runs of Sigma are much quicker - the first run after changes to the knowledge bases builds a large set of caches and indexes.  If there are no changes, subsequent runs just load a large serialized file.
